apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: my-wordpress
  name: mywordpress-config
data:
  MYSQL_DATABASE: password 
  MYSQL_USER: readWrite
  MYSQL_HOST: mysql
  MYSQL_RANDOM_ROOT_PASSWORD: '1'
