version: '3.1'
services:
  mytestedapp::
    image: localimage
    restart: always
    ports:
      - 8080:80
    environment:
      MYOTHERAPP: http://myotherapp:8088
    volumes:
      - vol1:/var/www/html
volumes:
  vol1:
networks:
  default:
    name: my-pre-existing-network
    external: true